[package]
authors = ["Carter Reeb <carter2k4@pm.me>"]
edition = "2018"
name = "rusty16"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.21.1"
colored = "2.0.0"
pad = "0.1.6"
